<?xml version="1.0" encoding="utf-8"?><Database Name="db_info" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;Initial Catalog=db_info;Integrated Security=True" SettingsObjectName="ProjetoFinalDAL.Properties.Settings" SettingsPropertyName="db_infoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categoria" Member="Categorias">
    <Type Name="Categoria">
      <Column Name="id_categoria" Member="codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ds_categoria" Member="descricao" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Categoria_Produto" Member="Produtos" ThisKey="codigo" OtherKey="codigo_categoria" Type="Produto" />
    </Type>
  </Table>
  <Table Name="dbo.Produto" Member="Produtos">
    <Type Name="Produto">
      <Column Name="id_produto" Member="codigo" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ds_produto" Member="descricao" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="valor" Type="System.Decimal" DbType="Decimal(15,2)" CanBeNull="true" />
      <Column Name="id_categoria" Member="codigo_categoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Categoria_Produto" Member="Categoria" ThisKey="codigo_categoria" OtherKey="codigo" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
</Database>